### ISSUE TITLE
Null Pointer Exception when trying app download offer

### ISSUE THREAD

**Issue by JimJty** [peanut-labs/publisher-android-sdk#1]
When I try to complete a Download App offer, I get a null pointer exception in the sdk. I can reproduce it every time with the attached offer.

![screen](https://cloud.githubusercontent.com/assets/2430388/17441485/254900b8-5ae6-11e6-9a4f-687098663551.png)

Here is a stack trace:
 java.lang.NullPointerException 
    at com.peanutlabs.plsdk.RewardsCenterActivity.setNavigationButtonsState(RewardsCenterActivity.java:153) 
    at com.peanutlabs.plsdk.RewardsCenterActivity.access$1(RewardsCenterActivity.java:145) 
    at com.peanutlabs.plsdk.RewardsCenterActivity$RewardsCenterWebChromeClient.onProgressChanged(RewardsCenterActivity.java:197)

**Comment by Bilguun39** [comment]
Hi Jim, 

Thanks for submitting this error, we tried to reproduce this error but couldn't, if you share us more detail informations would be super helpful.
1. Are you using latest sdk from our master branch?
2. Which device and android version you using?

**Comment by SideMoneyApps** [comment]
It looks like I wasn't using the latest PLSDK. I actually have a custom cordova plugin, however this latest PLSDK does not compile with it. Does the PLSDK used [here](https://github.com/peanut-labs/publisher-cordova-plugin) match this repo?
Also I don't see many Android app download offers, so I can't reproduce at the moment.
My test device is a Motorola Moto E, Android v4.4.4

**Comment by JimJty** [comment]
It looks like I wasn't using the latest PLSDK. I actually have a custom cordova plugin, however this latest PLSDK does not compile with it. Does the PLSDK used [here](https://github.com/peanut-labs/publisher-cordova-plugin) match this repo?
Also I don't see many Android app download offers, so I can't reproduce at the moment.
My test device is a Motorola Moto E, Android v4.4.4

**Comment by Bilguun39** [comment]
Thanks you for your response, cordova-plugin repo is not updated yet, we will update it shortly. Thank you

**Comment by VickyTapLane** [comment]
We're using the latest .aar in our Android app. We're getting a large number of crashes from the PLSDK:

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.net.URL.getPath()' on a null object reference
       at com.peanutlabs.plsdk.RewardsCenterActivity.setNavigationButtonsState(Unknown Source)
       at com.peanutlabs.plsdk.RewardsCenterActivity.setOrientationPermission(Unknown Source)
       at com.peanutlabs.plsdk.RewardsCenterActivity$RewardsCenterWebChromeClient.onProgressChanged(Unknown Source)
       at com.android.webview.chromium.WebViewContentsClientAdapter.onProgressChanged(WebViewContentsClientAdapter.java:251)
       at org.chromium.android_webview.AwContentsClientCallbackHelper$MyHandler.handleMessage(AwContentsClientCallbackHelper.java:210)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5857)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1026)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:887)

```
We traced the issue it seems to be due to the following code in the `RewardsCenterActivity`:
```
    private void setNavigationButtonsState() {
        WebView view = this._webView;
        URL url = null;

        try {
            url = new URL(view.getUrl());
        } catch (MalformedURLException var7) {
            ;
        }

        String path = url.getPath();
```

The try/catch doesn't do anything. This leaves `url` null when `url.getPath()` is called. Is there a way to prevent `MalformedURLException` from occurring? Is it possible to release a quick fix for this issue?

Thanks

**Comment by isamotiuc** [comment]
@VickyTapLane  @Bilguun39 We have the same problem, on .aar library. On the latest library .jar it doesnt work at all. It is crashing every time on start with `java.lang.ClassCastException`
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{test.test/com.peanutlabs.plsdk.RewardsCenterActivity}: java.lang.ClassCastException: android.widget.EditText cannot be cast to android.widget.RelativeLayout
              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2659)
              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724)
              at android.app.ActivityThread.-wrap12(ActivityThread.java)
              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
              at android.os.Handler.dispatchMessage(Handler.java:102)
              at android.os.Looper.loop(Looper.java:154)
              at android.app.ActivityThread.main(ActivityThread.java:6123)
              at java.lang.reflect.Method.invoke(Native Method)
              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
         Caused by: java.lang.ClassCastException: android.widget.EditText cannot be cast to android.widget.RelativeLayout
              at com.peanutlabs.plsdk.RewardsCenterActivity.initUI(RewardsCenterActivity.java:61)
              at com.peanutlabs.plsdk.RewardsCenterActivity.onCreate(RewardsCenterActivity.java:58)
              at android.app.Activity.performCreate(Activity.java:6672)
              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1140)
              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2612)
              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724) 
              at android.app.ActivityThread.-wrap12(ActivityThread.java) 
              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473) 
              at android.os.Handler.dispatchMessage(Handler.java:102) 
              at android.os.Looper.loop(Looper.java:154) 
              at android.app.ActivityThread.main(ActivityThread.java:6123) 
              at java.lang.reflect.Method.invoke(Native Method) 
              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867) 
              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757) 
```
Do you have any workaround on this problem? It would be very nice. Thank you.
